# Generated by Django 6.0.2 on 2026-03-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('residential_address_street_number', models.TextField()),
                ('residential_address_street_name', models.TextField()),
                ('residential_address_apartment_number', models.TextField(blank=True, null=True)),
                ('residential_address_zip_code', models.TextField()),
                ('date_of_birth', models.TextField()),
                ('date_of_registration', models.TextField()),
                ('party_affiliation', models.CharField(max_length=2)),
                ('precinct_number', models.TextField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
