# Generated by Django 6.0.2 on 2026-04-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_info', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('protocol_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_date', models.DateField()),
                ('screening_status', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.study')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('visit_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.visit')),
            ],
        ),
    ]
